Disable SXR. It is crashing the unidoc task.
In ScalatraTests:

    java.lang.IllegalArgumentException: requirement failed
	    at scala.Predef$.require(Predef.scala:145)
	    at sxr.FileUtil$.relativePath(FileUtil.scala:62)
	    at sxr.Browse.makeLink(Browse.scala:401)
	    at sxr.Browse.linkTo(Browse.scala:396)